// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/test/rpcservice.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2ftest_2frpcservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2ftest_2frpcservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "message/common/rpc.pb.h"
#include "service.h"
#include <memory>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2ftest_2frpcservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2ftest_2frpcservice_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2ftest_2frpcservice_2eproto;
namespace muduo {
namespace net {
class GetServiceRequest;
class GetServiceRequestDefaultTypeInternal;
extern GetServiceRequestDefaultTypeInternal _GetServiceRequest_default_instance_;
class GetServiceResponse;
class GetServiceResponseDefaultTypeInternal;
extern GetServiceResponseDefaultTypeInternal _GetServiceResponse_default_instance_;
class ListRpcRequest;
class ListRpcRequestDefaultTypeInternal;
extern ListRpcRequestDefaultTypeInternal _ListRpcRequest_default_instance_;
class ListRpcResponse;
class ListRpcResponseDefaultTypeInternal;
extern ListRpcResponseDefaultTypeInternal _ListRpcResponse_default_instance_;
}  // namespace net
}  // namespace muduo
PROTOBUF_NAMESPACE_OPEN
template<> ::muduo::net::GetServiceRequest* Arena::CreateMaybeMessage<::muduo::net::GetServiceRequest>(Arena*);
template<> ::muduo::net::GetServiceResponse* Arena::CreateMaybeMessage<::muduo::net::GetServiceResponse>(Arena*);
template<> ::muduo::net::ListRpcRequest* Arena::CreateMaybeMessage<::muduo::net::ListRpcRequest>(Arena*);
template<> ::muduo::net::ListRpcResponse* Arena::CreateMaybeMessage<::muduo::net::ListRpcResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace muduo {
namespace net {

// ===================================================================

class ListRpcRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:muduo.net.ListRpcRequest) */ {
 public:
  inline ListRpcRequest() : ListRpcRequest(nullptr) {}
  virtual ~ListRpcRequest();

  ListRpcRequest(const ListRpcRequest& from);
  ListRpcRequest(ListRpcRequest&& from) noexcept
    : ListRpcRequest() {
    *this = ::std::move(from);
  }

  inline ListRpcRequest& operator=(const ListRpcRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListRpcRequest& operator=(ListRpcRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ListRpcRequest& default_instance();

  static inline const ListRpcRequest* internal_default_instance() {
    return reinterpret_cast<const ListRpcRequest*>(
               &_ListRpcRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ListRpcRequest& a, ListRpcRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ListRpcRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListRpcRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ListRpcRequest* New() const final {
    return CreateMaybeMessage<ListRpcRequest>(nullptr);
  }

  ListRpcRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ListRpcRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ListRpcRequest& from);
  void MergeFrom(const ListRpcRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ListRpcRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "muduo.net.ListRpcRequest";
  }
  protected:
  explicit ListRpcRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2ftest_2frpcservice_2eproto);
    return ::descriptor_table_message_2ftest_2frpcservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceNameFieldNumber = 1,
    kListMethodFieldNumber = 2,
  };
  // string service_name = 1;
  void clear_service_name();
  const std::string& service_name() const;
  void set_service_name(const std::string& value);
  void set_service_name(std::string&& value);
  void set_service_name(const char* value);
  void set_service_name(const char* value, size_t size);
  std::string* mutable_service_name();
  std::string* release_service_name();
  void set_allocated_service_name(std::string* service_name);
  private:
  const std::string& _internal_service_name() const;
  void _internal_set_service_name(const std::string& value);
  std::string* _internal_mutable_service_name();
  public:

  // bool list_method = 2;
  void clear_list_method();
  bool list_method() const;
  void set_list_method(bool value);
  private:
  bool _internal_list_method() const;
  void _internal_set_list_method(bool value);
  public:

  // @@protoc_insertion_point(class_scope:muduo.net.ListRpcRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_name_;
  bool list_method_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2ftest_2frpcservice_2eproto;
};
// -------------------------------------------------------------------

class ListRpcResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:muduo.net.ListRpcResponse) */ {
 public:
  inline ListRpcResponse() : ListRpcResponse(nullptr) {}
  virtual ~ListRpcResponse();

  ListRpcResponse(const ListRpcResponse& from);
  ListRpcResponse(ListRpcResponse&& from) noexcept
    : ListRpcResponse() {
    *this = ::std::move(from);
  }

  inline ListRpcResponse& operator=(const ListRpcResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListRpcResponse& operator=(ListRpcResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ListRpcResponse& default_instance();

  static inline const ListRpcResponse* internal_default_instance() {
    return reinterpret_cast<const ListRpcResponse*>(
               &_ListRpcResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ListRpcResponse& a, ListRpcResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ListRpcResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListRpcResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ListRpcResponse* New() const final {
    return CreateMaybeMessage<ListRpcResponse>(nullptr);
  }

  ListRpcResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ListRpcResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ListRpcResponse& from);
  void MergeFrom(const ListRpcResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ListRpcResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "muduo.net.ListRpcResponse";
  }
  protected:
  explicit ListRpcResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2ftest_2frpcservice_2eproto);
    return ::descriptor_table_message_2ftest_2frpcservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceNameFieldNumber = 2,
    kMethodNameFieldNumber = 3,
    kErrorFieldNumber = 1,
  };
  // repeated string service_name = 2;
  int service_name_size() const;
  private:
  int _internal_service_name_size() const;
  public:
  void clear_service_name();
  const std::string& service_name(int index) const;
  std::string* mutable_service_name(int index);
  void set_service_name(int index, const std::string& value);
  void set_service_name(int index, std::string&& value);
  void set_service_name(int index, const char* value);
  void set_service_name(int index, const char* value, size_t size);
  std::string* add_service_name();
  void add_service_name(const std::string& value);
  void add_service_name(std::string&& value);
  void add_service_name(const char* value);
  void add_service_name(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& service_name() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_service_name();
  private:
  const std::string& _internal_service_name(int index) const;
  std::string* _internal_add_service_name();
  public:

  // repeated string method_name = 3;
  int method_name_size() const;
  private:
  int _internal_method_name_size() const;
  public:
  void clear_method_name();
  const std::string& method_name(int index) const;
  std::string* mutable_method_name(int index);
  void set_method_name(int index, const std::string& value);
  void set_method_name(int index, std::string&& value);
  void set_method_name(int index, const char* value);
  void set_method_name(int index, const char* value, size_t size);
  std::string* add_method_name();
  void add_method_name(const std::string& value);
  void add_method_name(std::string&& value);
  void add_method_name(const char* value);
  void add_method_name(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& method_name() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_method_name();
  private:
  const std::string& _internal_method_name(int index) const;
  std::string* _internal_add_method_name();
  public:

  // .muduo.net.ErrorCode error = 1;
  void clear_error();
  ::muduo::net::ErrorCode error() const;
  void set_error(::muduo::net::ErrorCode value);
  private:
  ::muduo::net::ErrorCode _internal_error() const;
  void _internal_set_error(::muduo::net::ErrorCode value);
  public:

  // @@protoc_insertion_point(class_scope:muduo.net.ListRpcResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> service_name_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> method_name_;
  int error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2ftest_2frpcservice_2eproto;
};
// -------------------------------------------------------------------

class GetServiceRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:muduo.net.GetServiceRequest) */ {
 public:
  inline GetServiceRequest() : GetServiceRequest(nullptr) {}
  virtual ~GetServiceRequest();

  GetServiceRequest(const GetServiceRequest& from);
  GetServiceRequest(GetServiceRequest&& from) noexcept
    : GetServiceRequest() {
    *this = ::std::move(from);
  }

  inline GetServiceRequest& operator=(const GetServiceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetServiceRequest& operator=(GetServiceRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetServiceRequest& default_instance();

  static inline const GetServiceRequest* internal_default_instance() {
    return reinterpret_cast<const GetServiceRequest*>(
               &_GetServiceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetServiceRequest& a, GetServiceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetServiceRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetServiceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetServiceRequest* New() const final {
    return CreateMaybeMessage<GetServiceRequest>(nullptr);
  }

  GetServiceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetServiceRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetServiceRequest& from);
  void MergeFrom(const GetServiceRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetServiceRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "muduo.net.GetServiceRequest";
  }
  protected:
  explicit GetServiceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2ftest_2frpcservice_2eproto);
    return ::descriptor_table_message_2ftest_2frpcservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceNameFieldNumber = 1,
  };
  // string service_name = 1;
  void clear_service_name();
  const std::string& service_name() const;
  void set_service_name(const std::string& value);
  void set_service_name(std::string&& value);
  void set_service_name(const char* value);
  void set_service_name(const char* value, size_t size);
  std::string* mutable_service_name();
  std::string* release_service_name();
  void set_allocated_service_name(std::string* service_name);
  private:
  const std::string& _internal_service_name() const;
  void _internal_set_service_name(const std::string& value);
  std::string* _internal_mutable_service_name();
  public:

  // @@protoc_insertion_point(class_scope:muduo.net.GetServiceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2ftest_2frpcservice_2eproto;
};
// -------------------------------------------------------------------

class GetServiceResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:muduo.net.GetServiceResponse) */ {
 public:
  inline GetServiceResponse() : GetServiceResponse(nullptr) {}
  virtual ~GetServiceResponse();

  GetServiceResponse(const GetServiceResponse& from);
  GetServiceResponse(GetServiceResponse&& from) noexcept
    : GetServiceResponse() {
    *this = ::std::move(from);
  }

  inline GetServiceResponse& operator=(const GetServiceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetServiceResponse& operator=(GetServiceResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetServiceResponse& default_instance();

  static inline const GetServiceResponse* internal_default_instance() {
    return reinterpret_cast<const GetServiceResponse*>(
               &_GetServiceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GetServiceResponse& a, GetServiceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetServiceResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetServiceResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetServiceResponse* New() const final {
    return CreateMaybeMessage<GetServiceResponse>(nullptr);
  }

  GetServiceResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetServiceResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetServiceResponse& from);
  void MergeFrom(const GetServiceResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetServiceResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "muduo.net.GetServiceResponse";
  }
  protected:
  explicit GetServiceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2ftest_2frpcservice_2eproto);
    return ::descriptor_table_message_2ftest_2frpcservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProtoFileFieldNumber = 2,
    kProtoFileNameFieldNumber = 3,
    kErrorFieldNumber = 1,
  };
  // repeated string proto_file = 2;
  int proto_file_size() const;
  private:
  int _internal_proto_file_size() const;
  public:
  void clear_proto_file();
  const std::string& proto_file(int index) const;
  std::string* mutable_proto_file(int index);
  void set_proto_file(int index, const std::string& value);
  void set_proto_file(int index, std::string&& value);
  void set_proto_file(int index, const char* value);
  void set_proto_file(int index, const char* value, size_t size);
  std::string* add_proto_file();
  void add_proto_file(const std::string& value);
  void add_proto_file(std::string&& value);
  void add_proto_file(const char* value);
  void add_proto_file(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& proto_file() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_proto_file();
  private:
  const std::string& _internal_proto_file(int index) const;
  std::string* _internal_add_proto_file();
  public:

  // repeated string proto_file_name = 3;
  int proto_file_name_size() const;
  private:
  int _internal_proto_file_name_size() const;
  public:
  void clear_proto_file_name();
  const std::string& proto_file_name(int index) const;
  std::string* mutable_proto_file_name(int index);
  void set_proto_file_name(int index, const std::string& value);
  void set_proto_file_name(int index, std::string&& value);
  void set_proto_file_name(int index, const char* value);
  void set_proto_file_name(int index, const char* value, size_t size);
  std::string* add_proto_file_name();
  void add_proto_file_name(const std::string& value);
  void add_proto_file_name(std::string&& value);
  void add_proto_file_name(const char* value);
  void add_proto_file_name(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& proto_file_name() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_proto_file_name();
  private:
  const std::string& _internal_proto_file_name(int index) const;
  std::string* _internal_add_proto_file_name();
  public:

  // .muduo.net.ErrorCode error = 1;
  void clear_error();
  ::muduo::net::ErrorCode error() const;
  void set_error(::muduo::net::ErrorCode value);
  private:
  ::muduo::net::ErrorCode _internal_error() const;
  void _internal_set_error(::muduo::net::ErrorCode value);
  public:

  // @@protoc_insertion_point(class_scope:muduo.net.GetServiceResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> proto_file_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> proto_file_name_;
  int error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2ftest_2frpcservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ListRpcRequest

// string service_name = 1;
inline void ListRpcRequest::clear_service_name() {
  service_name_.ClearToEmpty();
}
inline const std::string& ListRpcRequest::service_name() const {
  // @@protoc_insertion_point(field_get:muduo.net.ListRpcRequest.service_name)
  return _internal_service_name();
}
inline void ListRpcRequest::set_service_name(const std::string& value) {
  _internal_set_service_name(value);
  // @@protoc_insertion_point(field_set:muduo.net.ListRpcRequest.service_name)
}
inline std::string* ListRpcRequest::mutable_service_name() {
  // @@protoc_insertion_point(field_mutable:muduo.net.ListRpcRequest.service_name)
  return _internal_mutable_service_name();
}
inline const std::string& ListRpcRequest::_internal_service_name() const {
  return service_name_.Get();
}
inline void ListRpcRequest::_internal_set_service_name(const std::string& value) {
  
  service_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ListRpcRequest::set_service_name(std::string&& value) {
  
  service_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:muduo.net.ListRpcRequest.service_name)
}
inline void ListRpcRequest::set_service_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  service_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:muduo.net.ListRpcRequest.service_name)
}
inline void ListRpcRequest::set_service_name(const char* value,
    size_t size) {
  
  service_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:muduo.net.ListRpcRequest.service_name)
}
inline std::string* ListRpcRequest::_internal_mutable_service_name() {
  
  return service_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ListRpcRequest::release_service_name() {
  // @@protoc_insertion_point(field_release:muduo.net.ListRpcRequest.service_name)
  return service_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ListRpcRequest::set_allocated_service_name(std::string* service_name) {
  if (service_name != nullptr) {
    
  } else {
    
  }
  service_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), service_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:muduo.net.ListRpcRequest.service_name)
}

// bool list_method = 2;
inline void ListRpcRequest::clear_list_method() {
  list_method_ = false;
}
inline bool ListRpcRequest::_internal_list_method() const {
  return list_method_;
}
inline bool ListRpcRequest::list_method() const {
  // @@protoc_insertion_point(field_get:muduo.net.ListRpcRequest.list_method)
  return _internal_list_method();
}
inline void ListRpcRequest::_internal_set_list_method(bool value) {
  
  list_method_ = value;
}
inline void ListRpcRequest::set_list_method(bool value) {
  _internal_set_list_method(value);
  // @@protoc_insertion_point(field_set:muduo.net.ListRpcRequest.list_method)
}

// -------------------------------------------------------------------

// ListRpcResponse

// .muduo.net.ErrorCode error = 1;
inline void ListRpcResponse::clear_error() {
  error_ = 0;
}
inline ::muduo::net::ErrorCode ListRpcResponse::_internal_error() const {
  return static_cast< ::muduo::net::ErrorCode >(error_);
}
inline ::muduo::net::ErrorCode ListRpcResponse::error() const {
  // @@protoc_insertion_point(field_get:muduo.net.ListRpcResponse.error)
  return _internal_error();
}
inline void ListRpcResponse::_internal_set_error(::muduo::net::ErrorCode value) {
  
  error_ = value;
}
inline void ListRpcResponse::set_error(::muduo::net::ErrorCode value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:muduo.net.ListRpcResponse.error)
}

// repeated string service_name = 2;
inline int ListRpcResponse::_internal_service_name_size() const {
  return service_name_.size();
}
inline int ListRpcResponse::service_name_size() const {
  return _internal_service_name_size();
}
inline void ListRpcResponse::clear_service_name() {
  service_name_.Clear();
}
inline std::string* ListRpcResponse::add_service_name() {
  // @@protoc_insertion_point(field_add_mutable:muduo.net.ListRpcResponse.service_name)
  return _internal_add_service_name();
}
inline const std::string& ListRpcResponse::_internal_service_name(int index) const {
  return service_name_.Get(index);
}
inline const std::string& ListRpcResponse::service_name(int index) const {
  // @@protoc_insertion_point(field_get:muduo.net.ListRpcResponse.service_name)
  return _internal_service_name(index);
}
inline std::string* ListRpcResponse::mutable_service_name(int index) {
  // @@protoc_insertion_point(field_mutable:muduo.net.ListRpcResponse.service_name)
  return service_name_.Mutable(index);
}
inline void ListRpcResponse::set_service_name(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:muduo.net.ListRpcResponse.service_name)
  service_name_.Mutable(index)->assign(value);
}
inline void ListRpcResponse::set_service_name(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:muduo.net.ListRpcResponse.service_name)
  service_name_.Mutable(index)->assign(std::move(value));
}
inline void ListRpcResponse::set_service_name(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  service_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:muduo.net.ListRpcResponse.service_name)
}
inline void ListRpcResponse::set_service_name(int index, const char* value, size_t size) {
  service_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:muduo.net.ListRpcResponse.service_name)
}
inline std::string* ListRpcResponse::_internal_add_service_name() {
  return service_name_.Add();
}
inline void ListRpcResponse::add_service_name(const std::string& value) {
  service_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:muduo.net.ListRpcResponse.service_name)
}
inline void ListRpcResponse::add_service_name(std::string&& value) {
  service_name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:muduo.net.ListRpcResponse.service_name)
}
inline void ListRpcResponse::add_service_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  service_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:muduo.net.ListRpcResponse.service_name)
}
inline void ListRpcResponse::add_service_name(const char* value, size_t size) {
  service_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:muduo.net.ListRpcResponse.service_name)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ListRpcResponse::service_name() const {
  // @@protoc_insertion_point(field_list:muduo.net.ListRpcResponse.service_name)
  return service_name_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ListRpcResponse::mutable_service_name() {
  // @@protoc_insertion_point(field_mutable_list:muduo.net.ListRpcResponse.service_name)
  return &service_name_;
}

// repeated string method_name = 3;
inline int ListRpcResponse::_internal_method_name_size() const {
  return method_name_.size();
}
inline int ListRpcResponse::method_name_size() const {
  return _internal_method_name_size();
}
inline void ListRpcResponse::clear_method_name() {
  method_name_.Clear();
}
inline std::string* ListRpcResponse::add_method_name() {
  // @@protoc_insertion_point(field_add_mutable:muduo.net.ListRpcResponse.method_name)
  return _internal_add_method_name();
}
inline const std::string& ListRpcResponse::_internal_method_name(int index) const {
  return method_name_.Get(index);
}
inline const std::string& ListRpcResponse::method_name(int index) const {
  // @@protoc_insertion_point(field_get:muduo.net.ListRpcResponse.method_name)
  return _internal_method_name(index);
}
inline std::string* ListRpcResponse::mutable_method_name(int index) {
  // @@protoc_insertion_point(field_mutable:muduo.net.ListRpcResponse.method_name)
  return method_name_.Mutable(index);
}
inline void ListRpcResponse::set_method_name(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:muduo.net.ListRpcResponse.method_name)
  method_name_.Mutable(index)->assign(value);
}
inline void ListRpcResponse::set_method_name(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:muduo.net.ListRpcResponse.method_name)
  method_name_.Mutable(index)->assign(std::move(value));
}
inline void ListRpcResponse::set_method_name(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  method_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:muduo.net.ListRpcResponse.method_name)
}
inline void ListRpcResponse::set_method_name(int index, const char* value, size_t size) {
  method_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:muduo.net.ListRpcResponse.method_name)
}
inline std::string* ListRpcResponse::_internal_add_method_name() {
  return method_name_.Add();
}
inline void ListRpcResponse::add_method_name(const std::string& value) {
  method_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:muduo.net.ListRpcResponse.method_name)
}
inline void ListRpcResponse::add_method_name(std::string&& value) {
  method_name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:muduo.net.ListRpcResponse.method_name)
}
inline void ListRpcResponse::add_method_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  method_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:muduo.net.ListRpcResponse.method_name)
}
inline void ListRpcResponse::add_method_name(const char* value, size_t size) {
  method_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:muduo.net.ListRpcResponse.method_name)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ListRpcResponse::method_name() const {
  // @@protoc_insertion_point(field_list:muduo.net.ListRpcResponse.method_name)
  return method_name_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ListRpcResponse::mutable_method_name() {
  // @@protoc_insertion_point(field_mutable_list:muduo.net.ListRpcResponse.method_name)
  return &method_name_;
}

// -------------------------------------------------------------------

// GetServiceRequest

// string service_name = 1;
inline void GetServiceRequest::clear_service_name() {
  service_name_.ClearToEmpty();
}
inline const std::string& GetServiceRequest::service_name() const {
  // @@protoc_insertion_point(field_get:muduo.net.GetServiceRequest.service_name)
  return _internal_service_name();
}
inline void GetServiceRequest::set_service_name(const std::string& value) {
  _internal_set_service_name(value);
  // @@protoc_insertion_point(field_set:muduo.net.GetServiceRequest.service_name)
}
inline std::string* GetServiceRequest::mutable_service_name() {
  // @@protoc_insertion_point(field_mutable:muduo.net.GetServiceRequest.service_name)
  return _internal_mutable_service_name();
}
inline const std::string& GetServiceRequest::_internal_service_name() const {
  return service_name_.Get();
}
inline void GetServiceRequest::_internal_set_service_name(const std::string& value) {
  
  service_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void GetServiceRequest::set_service_name(std::string&& value) {
  
  service_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:muduo.net.GetServiceRequest.service_name)
}
inline void GetServiceRequest::set_service_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  service_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:muduo.net.GetServiceRequest.service_name)
}
inline void GetServiceRequest::set_service_name(const char* value,
    size_t size) {
  
  service_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:muduo.net.GetServiceRequest.service_name)
}
inline std::string* GetServiceRequest::_internal_mutable_service_name() {
  
  return service_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* GetServiceRequest::release_service_name() {
  // @@protoc_insertion_point(field_release:muduo.net.GetServiceRequest.service_name)
  return service_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GetServiceRequest::set_allocated_service_name(std::string* service_name) {
  if (service_name != nullptr) {
    
  } else {
    
  }
  service_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), service_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:muduo.net.GetServiceRequest.service_name)
}

// -------------------------------------------------------------------

// GetServiceResponse

// .muduo.net.ErrorCode error = 1;
inline void GetServiceResponse::clear_error() {
  error_ = 0;
}
inline ::muduo::net::ErrorCode GetServiceResponse::_internal_error() const {
  return static_cast< ::muduo::net::ErrorCode >(error_);
}
inline ::muduo::net::ErrorCode GetServiceResponse::error() const {
  // @@protoc_insertion_point(field_get:muduo.net.GetServiceResponse.error)
  return _internal_error();
}
inline void GetServiceResponse::_internal_set_error(::muduo::net::ErrorCode value) {
  
  error_ = value;
}
inline void GetServiceResponse::set_error(::muduo::net::ErrorCode value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:muduo.net.GetServiceResponse.error)
}

// repeated string proto_file = 2;
inline int GetServiceResponse::_internal_proto_file_size() const {
  return proto_file_.size();
}
inline int GetServiceResponse::proto_file_size() const {
  return _internal_proto_file_size();
}
inline void GetServiceResponse::clear_proto_file() {
  proto_file_.Clear();
}
inline std::string* GetServiceResponse::add_proto_file() {
  // @@protoc_insertion_point(field_add_mutable:muduo.net.GetServiceResponse.proto_file)
  return _internal_add_proto_file();
}
inline const std::string& GetServiceResponse::_internal_proto_file(int index) const {
  return proto_file_.Get(index);
}
inline const std::string& GetServiceResponse::proto_file(int index) const {
  // @@protoc_insertion_point(field_get:muduo.net.GetServiceResponse.proto_file)
  return _internal_proto_file(index);
}
inline std::string* GetServiceResponse::mutable_proto_file(int index) {
  // @@protoc_insertion_point(field_mutable:muduo.net.GetServiceResponse.proto_file)
  return proto_file_.Mutable(index);
}
inline void GetServiceResponse::set_proto_file(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:muduo.net.GetServiceResponse.proto_file)
  proto_file_.Mutable(index)->assign(value);
}
inline void GetServiceResponse::set_proto_file(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:muduo.net.GetServiceResponse.proto_file)
  proto_file_.Mutable(index)->assign(std::move(value));
}
inline void GetServiceResponse::set_proto_file(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  proto_file_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:muduo.net.GetServiceResponse.proto_file)
}
inline void GetServiceResponse::set_proto_file(int index, const char* value, size_t size) {
  proto_file_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:muduo.net.GetServiceResponse.proto_file)
}
inline std::string* GetServiceResponse::_internal_add_proto_file() {
  return proto_file_.Add();
}
inline void GetServiceResponse::add_proto_file(const std::string& value) {
  proto_file_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:muduo.net.GetServiceResponse.proto_file)
}
inline void GetServiceResponse::add_proto_file(std::string&& value) {
  proto_file_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:muduo.net.GetServiceResponse.proto_file)
}
inline void GetServiceResponse::add_proto_file(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  proto_file_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:muduo.net.GetServiceResponse.proto_file)
}
inline void GetServiceResponse::add_proto_file(const char* value, size_t size) {
  proto_file_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:muduo.net.GetServiceResponse.proto_file)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GetServiceResponse::proto_file() const {
  // @@protoc_insertion_point(field_list:muduo.net.GetServiceResponse.proto_file)
  return proto_file_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GetServiceResponse::mutable_proto_file() {
  // @@protoc_insertion_point(field_mutable_list:muduo.net.GetServiceResponse.proto_file)
  return &proto_file_;
}

// repeated string proto_file_name = 3;
inline int GetServiceResponse::_internal_proto_file_name_size() const {
  return proto_file_name_.size();
}
inline int GetServiceResponse::proto_file_name_size() const {
  return _internal_proto_file_name_size();
}
inline void GetServiceResponse::clear_proto_file_name() {
  proto_file_name_.Clear();
}
inline std::string* GetServiceResponse::add_proto_file_name() {
  // @@protoc_insertion_point(field_add_mutable:muduo.net.GetServiceResponse.proto_file_name)
  return _internal_add_proto_file_name();
}
inline const std::string& GetServiceResponse::_internal_proto_file_name(int index) const {
  return proto_file_name_.Get(index);
}
inline const std::string& GetServiceResponse::proto_file_name(int index) const {
  // @@protoc_insertion_point(field_get:muduo.net.GetServiceResponse.proto_file_name)
  return _internal_proto_file_name(index);
}
inline std::string* GetServiceResponse::mutable_proto_file_name(int index) {
  // @@protoc_insertion_point(field_mutable:muduo.net.GetServiceResponse.proto_file_name)
  return proto_file_name_.Mutable(index);
}
inline void GetServiceResponse::set_proto_file_name(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:muduo.net.GetServiceResponse.proto_file_name)
  proto_file_name_.Mutable(index)->assign(value);
}
inline void GetServiceResponse::set_proto_file_name(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:muduo.net.GetServiceResponse.proto_file_name)
  proto_file_name_.Mutable(index)->assign(std::move(value));
}
inline void GetServiceResponse::set_proto_file_name(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  proto_file_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:muduo.net.GetServiceResponse.proto_file_name)
}
inline void GetServiceResponse::set_proto_file_name(int index, const char* value, size_t size) {
  proto_file_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:muduo.net.GetServiceResponse.proto_file_name)
}
inline std::string* GetServiceResponse::_internal_add_proto_file_name() {
  return proto_file_name_.Add();
}
inline void GetServiceResponse::add_proto_file_name(const std::string& value) {
  proto_file_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:muduo.net.GetServiceResponse.proto_file_name)
}
inline void GetServiceResponse::add_proto_file_name(std::string&& value) {
  proto_file_name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:muduo.net.GetServiceResponse.proto_file_name)
}
inline void GetServiceResponse::add_proto_file_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  proto_file_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:muduo.net.GetServiceResponse.proto_file_name)
}
inline void GetServiceResponse::add_proto_file_name(const char* value, size_t size) {
  proto_file_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:muduo.net.GetServiceResponse.proto_file_name)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GetServiceResponse::proto_file_name() const {
  // @@protoc_insertion_point(field_list:muduo.net.GetServiceResponse.proto_file_name)
  return proto_file_name_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GetServiceResponse::mutable_proto_file_name() {
  // @@protoc_insertion_point(field_mutable_list:muduo.net.GetServiceResponse.proto_file_name)
  return &proto_file_name_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------



// ===================================================================

typedef     ::std::shared_ptr<ListRpcRequest>     ListRpcRequestPtr;
typedef     ::std::shared_ptr<ListRpcResponse>     ListRpcResponsePtr;
typedef     ::std::shared_ptr<GetServiceRequest>     GetServiceRequestPtr;
typedef     ::std::shared_ptr<GetServiceResponse>     GetServiceResponsePtr;

// -------------------------------------------------------------------

class RpcService_Stub;

class RpcService : public ::muduo::net::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline RpcService() {};
 public:
  virtual ~RpcService();

  typedef RpcService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void listRpc(const ::muduo::net::ListRpcRequestPtr& request,
                       const ::muduo::net::ListRpcResponsePtr& response);
  virtual void listRpc_DoneCb(const ::muduo::net::ListRpcRequestPtr& request,
                              const ::muduo::net::ListRpcResponsePtr& response) {} 
  virtual void listRpc_TimeOut(const ::muduo::net::ListRpcRequestPtr& request) {} 

  virtual void getService(const ::muduo::net::GetServiceRequestPtr& request,
                       const ::muduo::net::GetServiceResponsePtr& response);
  virtual void getService_DoneCb(const ::muduo::net::GetServiceRequestPtr& request,
                              const ::muduo::net::GetServiceResponsePtr& response) {} 
  virtual void getService_TimeOut(const ::muduo::net::GetServiceRequestPtr& request) {} 


  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  const ::google::protobuf::Message& GetRequestPrototype(
                             const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
                             const ::google::protobuf::MethodDescriptor* method) const;

  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  const ::google::protobuf::MessagePtr& request,
                  const ::google::protobuf::MessagePtr& response);

  void DoneCallback(const ::google::protobuf::MethodDescriptor* method,
                    const ::google::protobuf::MessagePtr& request,
                    const ::google::protobuf::MessagePtr& response);

  void TimeOut(const ::google::protobuf::MethodDescriptor* method,
               const ::google::protobuf::MessagePtr& request);

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(RpcService);
};

class RpcService_Stub : public RpcService {
 public:
  RpcService_Stub() {} 
  RpcService_Stub(::muduo::net::RpcChannelBase* channel);
  ~RpcService_Stub();

  inline ::muduo::net::RpcChannelBase* channel() { return channel_; }

  // implements RpcService ------------------------------------------

  virtual void listRpc(const ::muduo::net::ListRpcRequestPtr& request,
                       const ::muduo::net::ListRpcResponsePtr& response);
  virtual void getService(const ::muduo::net::GetServiceRequestPtr& request,
                       const ::muduo::net::GetServiceResponsePtr& response);

 private:
  muduo::net::RpcChannelBase* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(RpcService_Stub);
};

// @@protoc_insertion_point(namespace_scope)

}  // namespace net
}  // namespace muduo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2ftest_2frpcservice_2eproto
