// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/c2g_scene.proto

#include "service/c2g_scene.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace CMD {
class C2G_CreateEntryArgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<C2G_CreateEntryArg> _instance;
} _C2G_CreateEntryArg_default_instance_;
class C2G_CreateEntryResDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<C2G_CreateEntryRes> _instance;
} _C2G_CreateEntryRes_default_instance_;
class C2G_EnterSceneArgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<C2G_EnterSceneArg> _instance;
} _C2G_EnterSceneArg_default_instance_;
class C2G_EnterSceneResDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<C2G_EnterSceneRes> _instance;
} _C2G_EnterSceneRes_default_instance_;
}  // namespace CMD
static void InitDefaultsscc_info_C2G_CreateEntryArg_service_2fc2g_5fscene_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CMD::_C2G_CreateEntryArg_default_instance_;
    new (ptr) ::CMD::C2G_CreateEntryArg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_C2G_CreateEntryArg_service_2fc2g_5fscene_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_C2G_CreateEntryArg_service_2fc2g_5fscene_2eproto}, {}};

static void InitDefaultsscc_info_C2G_CreateEntryRes_service_2fc2g_5fscene_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CMD::_C2G_CreateEntryRes_default_instance_;
    new (ptr) ::CMD::C2G_CreateEntryRes();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_C2G_CreateEntryRes_service_2fc2g_5fscene_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_C2G_CreateEntryRes_service_2fc2g_5fscene_2eproto}, {}};

static void InitDefaultsscc_info_C2G_EnterSceneArg_service_2fc2g_5fscene_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CMD::_C2G_EnterSceneArg_default_instance_;
    new (ptr) ::CMD::C2G_EnterSceneArg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_C2G_EnterSceneArg_service_2fc2g_5fscene_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_C2G_EnterSceneArg_service_2fc2g_5fscene_2eproto}, {}};

static void InitDefaultsscc_info_C2G_EnterSceneRes_service_2fc2g_5fscene_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CMD::_C2G_EnterSceneRes_default_instance_;
    new (ptr) ::CMD::C2G_EnterSceneRes();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_C2G_EnterSceneRes_service_2fc2g_5fscene_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_C2G_EnterSceneRes_service_2fc2g_5fscene_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_service_2fc2g_5fscene_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_service_2fc2g_5fscene_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_service_2fc2g_5fscene_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_service_2fc2g_5fscene_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CMD::C2G_CreateEntryArg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CMD::C2G_CreateEntryRes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CMD::C2G_EnterSceneArg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CMD::C2G_EnterSceneRes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::CMD::C2G_CreateEntryArg)},
  { 5, -1, sizeof(::CMD::C2G_CreateEntryRes)},
  { 10, -1, sizeof(::CMD::C2G_EnterSceneArg)},
  { 15, -1, sizeof(::CMD::C2G_EnterSceneRes)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::CMD::_C2G_CreateEntryArg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::CMD::_C2G_CreateEntryRes_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::CMD::_C2G_EnterSceneArg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::CMD::_C2G_EnterSceneRes_default_instance_),
};

const char descriptor_table_protodef_service_2fc2g_5fscene_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027service/c2g_scene.proto\022\003CMD\"\024\n\022C2G_Cr"
  "eateEntryArg\"\024\n\022C2G_CreateEntryRes\"\023\n\021C2"
  "G_EnterSceneArg\"\023\n\021C2G_EnterSceneRes2\236\001\n"
  "\025C2G_SceneEntryService\022C\n\017C2G_CreateEntr"
  "y\022\027.CMD.C2G_CreateEntryArg\032\027.CMD.C2G_Cre"
  "ateEntryRes\022@\n\016C2G_EnterScene\022\026.CMD.C2G_"
  "EnterSceneArg\032\026.CMD.C2G_EnterSceneResb\006p"
  "roto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_service_2fc2g_5fscene_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_service_2fc2g_5fscene_2eproto_sccs[4] = {
  &scc_info_C2G_CreateEntryArg_service_2fc2g_5fscene_2eproto.base,
  &scc_info_C2G_CreateEntryRes_service_2fc2g_5fscene_2eproto.base,
  &scc_info_C2G_EnterSceneArg_service_2fc2g_5fscene_2eproto.base,
  &scc_info_C2G_EnterSceneRes_service_2fc2g_5fscene_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_service_2fc2g_5fscene_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_service_2fc2g_5fscene_2eproto = {
  false, false, descriptor_table_protodef_service_2fc2g_5fscene_2eproto, "service/c2g_scene.proto", 285,
  &descriptor_table_service_2fc2g_5fscene_2eproto_once, descriptor_table_service_2fc2g_5fscene_2eproto_sccs, descriptor_table_service_2fc2g_5fscene_2eproto_deps, 4, 0,
  schemas, file_default_instances, TableStruct_service_2fc2g_5fscene_2eproto::offsets,
  file_level_metadata_service_2fc2g_5fscene_2eproto, 4, file_level_enum_descriptors_service_2fc2g_5fscene_2eproto, file_level_service_descriptors_service_2fc2g_5fscene_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_service_2fc2g_5fscene_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_service_2fc2g_5fscene_2eproto)), true);
namespace CMD {

// ===================================================================

class C2G_CreateEntryArg::_Internal {
 public:
};

C2G_CreateEntryArg::C2G_CreateEntryArg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMD.C2G_CreateEntryArg)
}
C2G_CreateEntryArg::C2G_CreateEntryArg(const C2G_CreateEntryArg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CMD.C2G_CreateEntryArg)
}

void C2G_CreateEntryArg::SharedCtor() {
}

C2G_CreateEntryArg::~C2G_CreateEntryArg() {
  // @@protoc_insertion_point(destructor:CMD.C2G_CreateEntryArg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void C2G_CreateEntryArg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void C2G_CreateEntryArg::ArenaDtor(void* object) {
  C2G_CreateEntryArg* _this = reinterpret_cast< C2G_CreateEntryArg* >(object);
  (void)_this;
}
void C2G_CreateEntryArg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void C2G_CreateEntryArg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const C2G_CreateEntryArg& C2G_CreateEntryArg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_C2G_CreateEntryArg_service_2fc2g_5fscene_2eproto.base);
  return *internal_default_instance();
}


void C2G_CreateEntryArg::Clear() {
// @@protoc_insertion_point(message_clear_start:CMD.C2G_CreateEntryArg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2G_CreateEntryArg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* C2G_CreateEntryArg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMD.C2G_CreateEntryArg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMD.C2G_CreateEntryArg)
  return target;
}

size_t C2G_CreateEntryArg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMD.C2G_CreateEntryArg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void C2G_CreateEntryArg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CMD.C2G_CreateEntryArg)
  GOOGLE_DCHECK_NE(&from, this);
  const C2G_CreateEntryArg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<C2G_CreateEntryArg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CMD.C2G_CreateEntryArg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CMD.C2G_CreateEntryArg)
    MergeFrom(*source);
  }
}

void C2G_CreateEntryArg::MergeFrom(const C2G_CreateEntryArg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CMD.C2G_CreateEntryArg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void C2G_CreateEntryArg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CMD.C2G_CreateEntryArg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2G_CreateEntryArg::CopyFrom(const C2G_CreateEntryArg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMD.C2G_CreateEntryArg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2G_CreateEntryArg::IsInitialized() const {
  return true;
}

void C2G_CreateEntryArg::InternalSwap(C2G_CreateEntryArg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C2G_CreateEntryArg::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class C2G_CreateEntryRes::_Internal {
 public:
};

C2G_CreateEntryRes::C2G_CreateEntryRes(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMD.C2G_CreateEntryRes)
}
C2G_CreateEntryRes::C2G_CreateEntryRes(const C2G_CreateEntryRes& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CMD.C2G_CreateEntryRes)
}

void C2G_CreateEntryRes::SharedCtor() {
}

C2G_CreateEntryRes::~C2G_CreateEntryRes() {
  // @@protoc_insertion_point(destructor:CMD.C2G_CreateEntryRes)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void C2G_CreateEntryRes::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void C2G_CreateEntryRes::ArenaDtor(void* object) {
  C2G_CreateEntryRes* _this = reinterpret_cast< C2G_CreateEntryRes* >(object);
  (void)_this;
}
void C2G_CreateEntryRes::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void C2G_CreateEntryRes::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const C2G_CreateEntryRes& C2G_CreateEntryRes::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_C2G_CreateEntryRes_service_2fc2g_5fscene_2eproto.base);
  return *internal_default_instance();
}


void C2G_CreateEntryRes::Clear() {
// @@protoc_insertion_point(message_clear_start:CMD.C2G_CreateEntryRes)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2G_CreateEntryRes::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* C2G_CreateEntryRes::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMD.C2G_CreateEntryRes)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMD.C2G_CreateEntryRes)
  return target;
}

size_t C2G_CreateEntryRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMD.C2G_CreateEntryRes)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void C2G_CreateEntryRes::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CMD.C2G_CreateEntryRes)
  GOOGLE_DCHECK_NE(&from, this);
  const C2G_CreateEntryRes* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<C2G_CreateEntryRes>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CMD.C2G_CreateEntryRes)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CMD.C2G_CreateEntryRes)
    MergeFrom(*source);
  }
}

void C2G_CreateEntryRes::MergeFrom(const C2G_CreateEntryRes& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CMD.C2G_CreateEntryRes)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void C2G_CreateEntryRes::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CMD.C2G_CreateEntryRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2G_CreateEntryRes::CopyFrom(const C2G_CreateEntryRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMD.C2G_CreateEntryRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2G_CreateEntryRes::IsInitialized() const {
  return true;
}

void C2G_CreateEntryRes::InternalSwap(C2G_CreateEntryRes* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C2G_CreateEntryRes::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class C2G_EnterSceneArg::_Internal {
 public:
};

C2G_EnterSceneArg::C2G_EnterSceneArg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMD.C2G_EnterSceneArg)
}
C2G_EnterSceneArg::C2G_EnterSceneArg(const C2G_EnterSceneArg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CMD.C2G_EnterSceneArg)
}

void C2G_EnterSceneArg::SharedCtor() {
}

C2G_EnterSceneArg::~C2G_EnterSceneArg() {
  // @@protoc_insertion_point(destructor:CMD.C2G_EnterSceneArg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void C2G_EnterSceneArg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void C2G_EnterSceneArg::ArenaDtor(void* object) {
  C2G_EnterSceneArg* _this = reinterpret_cast< C2G_EnterSceneArg* >(object);
  (void)_this;
}
void C2G_EnterSceneArg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void C2G_EnterSceneArg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const C2G_EnterSceneArg& C2G_EnterSceneArg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_C2G_EnterSceneArg_service_2fc2g_5fscene_2eproto.base);
  return *internal_default_instance();
}


void C2G_EnterSceneArg::Clear() {
// @@protoc_insertion_point(message_clear_start:CMD.C2G_EnterSceneArg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2G_EnterSceneArg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* C2G_EnterSceneArg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMD.C2G_EnterSceneArg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMD.C2G_EnterSceneArg)
  return target;
}

size_t C2G_EnterSceneArg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMD.C2G_EnterSceneArg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void C2G_EnterSceneArg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CMD.C2G_EnterSceneArg)
  GOOGLE_DCHECK_NE(&from, this);
  const C2G_EnterSceneArg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<C2G_EnterSceneArg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CMD.C2G_EnterSceneArg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CMD.C2G_EnterSceneArg)
    MergeFrom(*source);
  }
}

void C2G_EnterSceneArg::MergeFrom(const C2G_EnterSceneArg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CMD.C2G_EnterSceneArg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void C2G_EnterSceneArg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CMD.C2G_EnterSceneArg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2G_EnterSceneArg::CopyFrom(const C2G_EnterSceneArg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMD.C2G_EnterSceneArg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2G_EnterSceneArg::IsInitialized() const {
  return true;
}

void C2G_EnterSceneArg::InternalSwap(C2G_EnterSceneArg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C2G_EnterSceneArg::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class C2G_EnterSceneRes::_Internal {
 public:
};

C2G_EnterSceneRes::C2G_EnterSceneRes(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMD.C2G_EnterSceneRes)
}
C2G_EnterSceneRes::C2G_EnterSceneRes(const C2G_EnterSceneRes& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CMD.C2G_EnterSceneRes)
}

void C2G_EnterSceneRes::SharedCtor() {
}

C2G_EnterSceneRes::~C2G_EnterSceneRes() {
  // @@protoc_insertion_point(destructor:CMD.C2G_EnterSceneRes)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void C2G_EnterSceneRes::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void C2G_EnterSceneRes::ArenaDtor(void* object) {
  C2G_EnterSceneRes* _this = reinterpret_cast< C2G_EnterSceneRes* >(object);
  (void)_this;
}
void C2G_EnterSceneRes::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void C2G_EnterSceneRes::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const C2G_EnterSceneRes& C2G_EnterSceneRes::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_C2G_EnterSceneRes_service_2fc2g_5fscene_2eproto.base);
  return *internal_default_instance();
}


void C2G_EnterSceneRes::Clear() {
// @@protoc_insertion_point(message_clear_start:CMD.C2G_EnterSceneRes)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2G_EnterSceneRes::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* C2G_EnterSceneRes::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMD.C2G_EnterSceneRes)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMD.C2G_EnterSceneRes)
  return target;
}

size_t C2G_EnterSceneRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMD.C2G_EnterSceneRes)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void C2G_EnterSceneRes::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CMD.C2G_EnterSceneRes)
  GOOGLE_DCHECK_NE(&from, this);
  const C2G_EnterSceneRes* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<C2G_EnterSceneRes>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CMD.C2G_EnterSceneRes)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CMD.C2G_EnterSceneRes)
    MergeFrom(*source);
  }
}

void C2G_EnterSceneRes::MergeFrom(const C2G_EnterSceneRes& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CMD.C2G_EnterSceneRes)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void C2G_EnterSceneRes::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CMD.C2G_EnterSceneRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2G_EnterSceneRes::CopyFrom(const C2G_EnterSceneRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMD.C2G_EnterSceneRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2G_EnterSceneRes::IsInitialized() const {
  return true;
}

void C2G_EnterSceneRes::InternalSwap(C2G_EnterSceneRes* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C2G_EnterSceneRes::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

C2G_SceneEntryService::~C2G_SceneEntryService() {}

static const ::google::protobuf::ServiceDescriptor* C2G_SceneEntryService_descriptor_ = NULL;

const ::google::protobuf::ServiceDescriptor* C2G_SceneEntryService::descriptor() {
  // protobuf_AssignDescriptorsOnce();
  if (C2G_SceneEntryService_descriptor_ == NULL)
    C2G_SceneEntryService_descriptor_ = ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
        "service/c2g_scene.proto")->service(0);
  return C2G_SceneEntryService_descriptor_;
}

const ::google::protobuf::ServiceDescriptor* C2G_SceneEntryService::GetDescriptor() {
  return descriptor();
}

void C2G_SceneEntryService::C2G_CreateEntry(const ::CMD::C2G_CreateEntryArgPtr&,
                         const ::CMD::C2G_CreateEntryResPtr&) {
  assert(0);
}

void C2G_SceneEntryService::C2G_EnterScene(const ::CMD::C2G_EnterSceneArgPtr&,
                         const ::CMD::C2G_EnterSceneResPtr&) {
  assert(0);
}

void C2G_SceneEntryService::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             const ::google::protobuf::MessagePtr& request,
                             const ::google::protobuf::MessagePtr& response) {
  GOOGLE_DCHECK_EQ(method->service(), C2G_SceneEntryService_descriptor_);
  switch(method->index()) {
    case 0:
      C2G_CreateEntry(::google::protobuf::down_pointer_cast<::CMD::C2G_CreateEntryArg>(request),
             ::google::protobuf::down_pointer_cast<::CMD::C2G_CreateEntryRes>(response));
      break;
    case 1:
      C2G_EnterScene(::google::protobuf::down_pointer_cast<::CMD::C2G_EnterSceneArg>(request),
             ::google::protobuf::down_pointer_cast<::CMD::C2G_EnterSceneRes>(response));
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

void C2G_SceneEntryService::DoneCallback(const ::google::protobuf::MethodDescriptor* method,
                               const ::google::protobuf::MessagePtr& request,
                               const ::google::protobuf::MessagePtr& response) {
  GOOGLE_DCHECK_EQ(method->service(), C2G_SceneEntryService_descriptor_);
  switch(method->index()) {
    case 0:
      C2G_CreateEntry_DoneCb(::google::protobuf::down_pointer_cast<::CMD::C2G_CreateEntryArg>(request),
                    ::google::protobuf::down_pointer_cast<::CMD::C2G_CreateEntryRes>(response));
      break;
    case 1:
      C2G_EnterScene_DoneCb(::google::protobuf::down_pointer_cast<::CMD::C2G_EnterSceneArg>(request),
                    ::google::protobuf::down_pointer_cast<::CMD::C2G_EnterSceneRes>(response));
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

void C2G_SceneEntryService::TimeOut(const ::google::protobuf::MethodDescriptor* method,
                          const ::google::protobuf::MessagePtr& request) {
  GOOGLE_DCHECK_EQ(method->service(), C2G_SceneEntryService_descriptor_);
  switch(method->index()) {
    case 0:
      C2G_CreateEntry_TimeOut(::google::protobuf::down_pointer_cast<::CMD::C2G_CreateEntryArg>(request));
      break;
    case 1:
      C2G_EnterScene_TimeOut(::google::protobuf::down_pointer_cast<::CMD::C2G_EnterSceneArg>(request));
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& C2G_SceneEntryService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::CMD::C2G_CreateEntryArg::default_instance();
    case 1:
      return ::CMD::C2G_EnterSceneArg::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

const ::google::protobuf::Message& C2G_SceneEntryService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::CMD::C2G_CreateEntryRes::default_instance();
    case 1:
      return ::CMD::C2G_EnterSceneRes::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

C2G_SceneEntryService_Stub::C2G_SceneEntryService_Stub(::muduo::net::RpcChannelBase* channel__)
    : channel_(channel__), owns_channel_(false) 
{
}

C2G_SceneEntryService_Stub::~C2G_SceneEntryService_Stub() 
{
}

void C2G_SceneEntryService_Stub::C2G_CreateEntry(const ::CMD::C2G_CreateEntryArgPtr& request,
                              const ::CMD::C2G_CreateEntryResPtr& response) 
{
  channel_->CallMethod(descriptor()->method(0),
                       request, 
                       response);
}

void C2G_SceneEntryService_Stub::C2G_EnterScene(const ::CMD::C2G_EnterSceneArgPtr& request,
                              const ::CMD::C2G_EnterSceneResPtr& response) 
{
  channel_->CallMethod(descriptor()->method(1),
                       request, 
                       response);
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace CMD
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CMD::C2G_CreateEntryArg* Arena::CreateMaybeMessage< ::CMD::C2G_CreateEntryArg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMD::C2G_CreateEntryArg >(arena);
}
template<> PROTOBUF_NOINLINE ::CMD::C2G_CreateEntryRes* Arena::CreateMaybeMessage< ::CMD::C2G_CreateEntryRes >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMD::C2G_CreateEntryRes >(arena);
}
template<> PROTOBUF_NOINLINE ::CMD::C2G_EnterSceneArg* Arena::CreateMaybeMessage< ::CMD::C2G_EnterSceneArg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMD::C2G_EnterSceneArg >(arena);
}
template<> PROTOBUF_NOINLINE ::CMD::C2G_EnterSceneRes* Arena::CreateMaybeMessage< ::CMD::C2G_EnterSceneRes >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMD::C2G_EnterSceneRes >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
