// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/service_enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_service_2fservice_5fenum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_service_2fservice_5fenum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_service_2fservice_5fenum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_service_2fservice_5fenum_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_service_2fservice_5fenum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace ENUM {

enum EServiceType : int {
  SERVICETYPE_MIN = 0,
  C2G_MIN = 1,
  C2G_UserLoginService = 2,
  C2G_UserLoginService_Stub = 3,
  C2G_SceneEntryService = 4,
  C2G_SceneEntryService_Stub = 5,
  C2G_MAX = 240,
  G2C_MIN = 241,
  G2C_SceneService = 242,
  G2C_SceneService_Stub = 243,
  G2C_MAX = 480,
  SudokuService = 501,
  SudokuService_Stub = 502,
  SERVICETYPE_MAX = 1024,
  EServiceType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  EServiceType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool EServiceType_IsValid(int value);
constexpr EServiceType EServiceType_MIN = SERVICETYPE_MIN;
constexpr EServiceType EServiceType_MAX = SERVICETYPE_MAX;
constexpr int EServiceType_ARRAYSIZE = EServiceType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EServiceType_descriptor();
template<typename T>
inline const std::string& EServiceType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EServiceType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EServiceType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EServiceType_descriptor(), enum_t_value);
}
inline bool EServiceType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EServiceType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EServiceType>(
    EServiceType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ENUM

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ENUM::EServiceType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ENUM::EServiceType>() {
  return ::ENUM::EServiceType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_service_2fservice_5fenum_2eproto
